Models/MeetingInfo.cs
namespace MeetingApp.Models //Bu bilgileri HomeController.cs dosyası alması için hazırlandı.
{
    public class MeetingInfo
    {
        public int Id { get; set; }

        public string? Location { get; set; }

        public DateTime Date { get; set; }


        public int NumberOfPeople { get; set; }







    }


}

Models/Repository.cs
using Microsoft.AspNetCore.Authorization.Infrastructure;

namespace MeetingApp.Models
{

    public static class Repository
    {

        private static List<UserInfo> _users = new();

        static Repository()
        {

            _users.Add(new UserInfo() { Id = 1, Name = "Ali", Email = "abc@gmail.com", Phone = "11111", WillAttend = true });
            _users.Add(new UserInfo() { Id = 2, Name = "Ahmet", Email = "abcd@gmail.com", Phone = "22222", WillAttend = false });
            _users.Add(new UserInfo() { Id = 3, Name = "Canan", Email = "abce@gmail.com", Phone = "33333", WillAttend = true });


        }

        public static List<UserInfo> Users
        {

            get
            {

                return _users;


            }



        }

        public static void CreateUser(UserInfo user)
        {


            user.Id = Users.Count + 1;
            _users.Add(user);


        }

        public static UserInfo? GetById(int id)

        {

            return _users.FirstOrDefault(user => user.Id == id);
}

    }


}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{

    public class UserInfo
    {


        public int Id { get; set; }

        [Required(ErrorMessage ="Ad alanı zorunlu")]
        public string? Name { get; set; }

        [Required(ErrorMessage ="Telefon alanı zorunlu")]

        public string? Phone { get; set; }

        [Required (ErrorMessage ="Email alanı zorunlu")]
        [EmailAddress(ErrorMessage ="Hatalı email")]

        public string? Email { get; set; }
        
        [Required(ErrorMessage ="Katılım durmunu belirtiniz.")]
        
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models; // MeetingInfo class'ı burada

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        // localhost
        // localhost/home
        // localhost/home/index
        public IActionResult Index()
        {

        

            int saat = DateTime.Now.Hour;

            // ViewBag yerine ViewData ile dinamik veri gönderiyoruz
            ViewData["Selamlama"] = saat > 12 ? "İyi günler" : "Günaydın";

            int UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
            //ViewData["UserName"] = "Çınar";

            var MeetingInfo = new MeetingInfo()
            {
                Id = 1,
                Location = "İstanbul, Abc Kongre Merkezi",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = UserCount
            };

            // 🔥 Burada modeli View'e gönderiyoruz
            return View(MeetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;//3. işlem-Controller sınıfının namespace'i

using MeetingApp.Models;

namespace MeetingApp.Controllers//1. işlem-MeetingApp projesi altında controller namespace'i tanımlıyoruz   
{

    public class MeetingController : Controller//2. işlem-MeetingApp projesi altında controller namespace'nin içinde MeetingController class'ı tanımlanıyor
    {
        
        [HttpGet]
        public IActionResult Apply()

        {

            return View();//4. işlem-MeetingController class’ın action metodu oluyor. Views\Meeting\Apply.cshtml'e gönderme yapıyor.

        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)

        {
            if (ModelState.IsValid)
            {
                Repository.CreateUser(model);

                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();

                return View("Thanks", model);//4. işlem-MeetingController class’ın action metodu oluyor. Views\Meeting\Apply.cshtml'e gönderme yapıyor. 

            }
            else
            {
                return View(model);
            }

            

        }

        [HttpGet]
        public IActionResult List()

        {

            return View(Repository.Users);//4. işlem-MeetingController class’ın action metodu oluyor. Views\Meeting\List.cshtml'e gönderme yapıyor.

        }

//meeting/details/2
        public IActionResult Details(int id)
        {

            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Toplantı Başvuru"; // Layout ile başlık kullanımı
    Layout = "_Layout2"; // İkinci layout'u kullanıyoruz
}

<main class="text-center">
<h1 class="h4">@ViewData["Selamlama"]</h1>
<p>Toplantı katılım durumunuzu bildirin.</p>

<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.Location</li>
        <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek </li>
        <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
</div>

<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>

</main>

Views/Meeting/Apply.cshtml
@model UserInfo


@{

ViewBag.Title = "Başvuru Formu"; //ViewBag'in Layout ile kullanımı



}



<h1 class="h4 text-center">Toplantı katılım formu</h1>

<form method="post" action="/Meeting/Apply" novalidate>

<div asp-validation-summary="All"></div>

    <div class="mb-3">

    <label asp-for="Name" class="form-label">Ad Soyad</label>

    <input asp-for="Name" class="form-control">

    </div>

    <div class="mb-3">

    <label asp-for="Phone" class="form-label">Telefon</label>
    
    <input asp-for="Phone" class="form-control">
    
    </div>    

    <div class="mb-3">

    <label asp-for="Email" class="form-label">Eposta</label>
    
    <input asp-for="Email" class="form-control">
    
    </div>   

    <div class="mb-3">

    <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
    
    <select asp-for="WillAttend" class="form-select">

    <option value="">Seçiniz</option>

    <option value="true">Evet, Geliyorum</option>

    <option value="false">Hayır, Gelmiyorum</option>

    </select>
    
    </div>  
    

<button class="btn btn-primary" type="submit">Kaydet</button>

</form>

Views/Meeting/Details.cshtml
@model UserInfo

@{
ViewBag.Title="Başvuru Detayı";

}

@{

var className=@Model.WillAttend==true ? "primary":"danger";

}


<main class="text-center">

    <h1 class=h4>Başvuru Detayı</h1>

    <p>

        <span class="badge text-bg-@className">

@if(Model.WillAttend==true){


    <text>Katılıyor</text>

    
}else{

    <text>Katılmıyor</text>
}

        </span>
    </p>

    <p>İsim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Telefon: @Model.Phone</p>

    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>

</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{

ViewBag.Title = "Toplantıya Katılım Listesi"; //ViewBag'in Layout ile kullanımı

}

<main class="text-center">

<h1 class="h4">Toplantıya Katılım Listesi</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Ad</td>               
            <td>Katılım durumu</td>
            <td></td>
        </tr>
    </thead>

<tbody>

    @{int i=0;}

@foreach(var user in Model){

    var durum = user.WillAttend ==true ? "Evet":"Hayır";

    var className =user.WillAttend==true ? "table-success": "table-danger";

    if (user.WillAttend==true){

i++;

    }

    <tr class="@className">
    <td>@user.Name</td>    
    <td>@durum</td>
    <td>
    <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
    </td>
    </tr>


}

    

   
</tbody>
</table>

<div class="card">

    <div class="card-body">
        <span>Katılımcı sayısı:@i</span>
    </div>
</div>

</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{    
    
    ViewBag.Title = "Başvuru Durumu"; //ViewBag'in Layout ile kullanımı 
}

<main class="text-center">

<h1 class="h4">Başvuru Durumu</h1>


@if (Model.WillAttend==true){

<p>Teşekkürler, @Model.Name, toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
<a btn class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>

}else{

    <p>@Model.Name, katılmadığından dolayı üzgünüz.</p>
    <a btn class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>


}


</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" /> @*Bu sayfaya Bootstrap kütüphanesini bu şekilde dahil etmiş oluyoruz. Aşağıdaki ViewBag.Title'in Layout ile kullanımı  *@

    <link rel="stylesheet" href="/css/styles.css" />
    <title>@ViewBag.Title-MeetingApp</title>
</head>
<body>
<div class="bg-primary text white p-2 text-center">
MeetingApp
</div>
<div class="container mt-3">
<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="card">
            <div class="card-body">
            @RenderBody() @*RenderBody View'leri Layout'un burasına bağlıyor*@                
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    @* Bootstrap kütüphanesi dahil edildi *@
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>

    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card shadow-sm">
                    <div class="card-body">
                        @RenderBody() 
                        @* RenderBody ile ilgili View bu noktada görünecek *@                
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>